name: Lint Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install requirements
        run: pip install -r requirements/lint.txt

      - name: Check with black
        run: black --check .

      - name: Check with isort
        run: isort --check-only --verbose .